---
apiVersion: v1
kind: Service
metadata:
  name: freertos-service
  namespace: embedded-os
  labels:
    app: freertos
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: freertos
---
apiVersion: v1
kind: Service
metadata:
  name: mbed-service
  namespace: embedded-os
  labels:
    app: mbed-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: mbed-app
---
apiVersion: v1
kind: Service
metadata:
  name: zephyr-service
  namespace: embedded-os
  labels:
    app: zephyr
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: zephyr
